# Generated by Django 5.1.7 on 2025-04-26 14:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="details",
            name="location",
            field=models.CharField(default="", max_length=100),
        ),
    ]
